id: detonate_url_-_joesecurity
version: -1
name: Detonate URL - JoeSecurity
fromversion: 6.8.0
description: |-
  This playbook uploads, detonates, and analyzes URLs for the JoeSecurity Sandbox.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 9cbcdcb1-0cf1-42ce-889a-e6f6669d180a
    type: start
    task:
      id: 9cbcdcb1-0cf1-42ce-889a-e6f6669d180a
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 445,
          "y": 40
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    continueonerrortype: ""
    isautoswitchedtoquietmode: false
    isoversize: false
    quietmode: 0
    skipunavailable: false
  "1":
    id: "1"
    taskid: 796e163e-a268-481c-89cb-d75c3c93e632
    type: title
    task:
      id: 796e163e-a268-481c-89cb-d75c3c93e632
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 445,
          "y": 1500
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    continueonerrortype: ""
    isautoswitchedtoquietmode: false
    isoversize: false
    quietmode: 0
    skipunavailable: false
  "2":
    id: "2"
    taskid: e0fad0ed-2ecc-46c7-8699-a89fba59223a
    type: condition
    task:
      id: e0fad0ed-2ecc-46c7-8699-a89fba59223a
      version: -1
      name: Is there a URL to detonate?
      description: |-
        Look for URL to detonate.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "1"
      "yes":
      - "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 750,
          "y": 760
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.URL
          operator: isNotEmpty
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    isautoswitchedtoquietmode: false
    isoversize: false
    quietmode: 0
    skipunavailable: false
  "3":
    id: "3"
    taskid: 7fd7bfb9-2d88-4ed9-862b-45d9d7871f49
    type: condition
    task:
      id: 7fd7bfb9-2d88-4ed9-862b-45d9d7871f49
      version: -1
      name: Is JoeSecurity sandbox enabled?
      description: "Returns 'yes' if integration brand is available. Otherwise returns 'no'."
      type: condition
      iscommand: false
      brand: ""
      scriptName: IsIntegrationAvailable
    nexttasks:
      '#default#':
      - "1"
      "yes":
      - "7"
    scriptarguments:
      brandname:
        simple: JoeSecurityV2
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 445,
          "y": 215
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    continueonerrortype: ""
    isautoswitchedtoquietmode: false
    isoversize: false
    quietmode: 0
    results:
    - brandInstances
    skipunavailable: false
  "5":
    id: "5"
    taskid: 2d3a4187-fed2-4171-88e6-f12874a58da1
    type: regular
    task:
      id: 2d3a4187-fed2-4171-88e6-f12874a58da1
      version: -1
      name: Check Joe Security Sandbox Quota
      description: "Retrieve the account quota."
      type: regular
      iscommand: true
      brand: ""
      script: '|||joe-get-account-quota'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 750,
          "y": 970
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    continueonerrortype: ""
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    quietmode: 0
    skipunavailable: false
  "6":
    id: "6"
    taskid: 56d80c66-cf21-4e32-8647-fa76a90199ed
    type: condition
    task:
      id: 56d80c66-cf21-4e32-8647-fa76a90199ed
      version: -1
      name: Is there enough quota for submission?
      description: Is there enough quota for submission?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "1"
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: greaterThan
          left:
            value:
              simple: Joe.AccountQuota.quota.daily.remaining
            iscontext: true
          right:
            value:
              simple: "0"
    view: |-
      {
        "position": {
          "x": 750,
          "y": 1130
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    continueonerrortype: ""
    isautoswitchedtoquietmode: false
    isoversize: false
    quietmode: 0
    skipunavailable: false
  "7":
    id: "7"
    taskid: e291ee66-1238-4b59-82b1-a68226035c4d
    type: regular
    task:
      id: e291ee66-1238-4b59-82b1-a68226035c4d
      version: -1
      name: Get Joe Sandbox Status
      description: Check if the Joe Sandbox analysis backend is online or in maintenance mode.
      type: regular
      iscommand: true
      brand: "JoeSecurityV2"
      script: JoeSecurityV2|||joe-is-online
    nexttasks:
      '#none#':
      - "8"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 750,
          "y": 390
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    continueonerrortype: ""
    isautoswitchedtoquietmode: false
    isoversize: false
    quietmode: 0
    skipunavailable: false
  "8":
    id: "8"
    taskid: 98d18248-2819-4536-8814-1c3de4709bd6
    type: condition
    task:
      id: 98d18248-2819-4536-8814-1c3de4709bd6
      version: -1
      name: Check if Joe Security is online
      description: Check if Joe Security is online.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "1"
      "yes":
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 750,
          "y": 550
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: Joe.ServerStatus.Online
          operator: isTrue
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    isautoswitchedtoquietmode: false
    isoversize: false
    quietmode: 0
    skipunavailable: false
  "4":
    continueonerrortype: ""
    evidencedata:
      customfields: {}
      description:
        simple: Joe Security - Submission Analysis
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      archive_password:
        complex:
          root: inputs.ArchivePassword
          transformers:
          - operator: uniq
      command_line_argument:
        complex:
          root: inputs.CommandLineArgument
          transformers:
          - operator: uniq
      comments:
        complex:
          root: inputs.Comments
      document_password:
        complex:
          root: inputs.DocumentPassword
          transformers:
          - operator: uniq
      email_notification:
        complex:
          root: inputs.EmailNotification
      encrypt_with_password:
        complex:
          root: inputs.EncryptWithPassword
          transformers:
          - operator: uniq
      fast_mode:
        complex:
          root: inputs.FastMode
          transformers:
          - operator: uniq
      hybrid_code_analysis:
        complex:
          root: inputs.HybridCodeAnalysis
          transformers:
          - operator: uniq
      internet_access:
        complex:
          root: inputs.InternetAccess
          transformers:
          - operator: uniq
      report_type:
        complex:
          root: inputs.ReportFileType
          transformers:
          - operator: uniq
      ssl_inspection:
        complex:
          root: inputs.SSLInspection
      start_as_normal_user:
        complex:
          root: inputs.StartAsNormalUser
      systems:
        complex:
          root: inputs.Systems
          transformers:
          - operator: uniq
      tags:
        complex:
          root: inputs.Tags
          transformers:
          - operator: uniq
      timeout:
        complex:
          root: inputs.Timeout
      url:
        complex:
          root: inputs.URL
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Submit an URL for sandbox analysis.
      id: b08b4eaa-129d-4d7a-85c9-f9319e70a0b5
      iscommand: true
      name: 'Detonate URL - Joe Security Sandbox '
      script: '|||joe-submit-url'
      type: regular
      version: -1
    taskid: b08b4eaa-129d-4d7a-85c9-f9319e70a0b5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 750,
          "y": 1330
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1525,
        "width": 685,
        "x": 445,
        "y": 40
      }
    }
  }
inputs:
- key: URL
  value: {}
  required: false
  description: The details of the URL to detonate
  playbookInputQuery:
- key: Timeout
  value:
    simple: "1200"
  required: false
  description: The duration after which to stop pooling and to resume the playbook (in minutes).
  playbookInputQuery:
- key: Systems
  value: {}
  required: false
  description: 'Comma-separated list of operating systems to run the analysis on. Supported values are: w7, w7x64, w7_1, w7_2, w7native, android2, android3, mac1, w7l, w7x64l, w10, android4, w7x64native, w7_3, w10native, android5native_1, w7_4, w7_5, w10x64, w7x64_hvm, android6, iphone1, w7_sec, macvm, w7_lang_packs, w7x64native_hvm, lnxubuntu1, lnxcentos1, android7_nougat'
  playbookInputQuery:
- key: Comments
  value: {}
  required: false
  description: Comments for the analysis.
  playbookInputQuery:
- key: InternetAccess
  value:
    simple: "True"
  required: false
  description: Enable internet access (boolean). True= internet access (default), False= no internet access.
  playbookInputQuery:
- key: ReportFileType
  value: {}
  required: false
  description: 'The resource type to download. Default is html. Supported values are: html, lighthtml, executive, pdf, classhtml, xml, lightxml, classxml, clusterxml, irxml, json, jsonfixed, lightjson, lightjsonfixed, irjson, irjsonfixed, shoots (screenshots), openioc, maec, misp, graphreports, memstrings, binstrings, sample, cookbook, bins (dropped files), unpackpe (unpacked PE files), unpack, ida, pcap, pcapslim, memdumps, yara'
  playbookInputQuery:
- description: A comma-separated list of tags to be added to the analysis.
  key: Tags
  playbookInputQuery:
  required: false
  value: {}
- description: Whether to enable SSL inspection.
  key: SSLInspection
  playbookInputQuery:
  required: false
  value:
    simple: "False"
- description: Whether to enable hybrid code analysis.
  key: HybridCodeAnalysis
  playbookInputQuery:
  required: false
  value:
    simple: "True"
- description: Whether to enable fast mode. Focuses on fast analysis and detection versus deep forensic analysis.
  key: FastMode
  playbookInputQuery:
  required: false
  value:
    simple: "false"
- description: A command line argument is to be passed to the sample.
  key: CommandLineArgument
  playbookInputQuery:
  required: false
  value: {}
- description: The document password.
  key: DocumentPassword
  playbookInputQuery:
  required: false
  value: {}
- description: An archive password.
  key: ArchivePassword
  playbookInputQuery:
  required: false
  value: {}
- description: Send an email notification once the analysis completes.
  key: EmailNotification
  playbookInputQuery:
  required: false
  value:
    simple: "False"
- description: Whether to start the analysis as a normal user.
  key: StartAsNormalUser
  playbookInputQuery:
  required: false
  value:
    simple: "False"
- description: The password to encrypt the analysis with.
  key: EncryptWithPassword
  playbookInputQuery:
  required: false
  value: {}
outputs:
- contextPath: DBotScore
  description: The DBot score of the suspicious URL
  type: unknown
- contextPath: Joe.Analysis
  description: The sandbox analysis details
  type: unknown
- contextPath: Joe.Submission.most_relevant_analysis
  description: The URL verdict of the sandbox analysis
  type: unknown
tests:
- JoeSecurityTestDetonation
