id: detonate_url_-_generic
version: -1
name: Detonate URL - Generic
description: |
  This playbook uploads, detonates URLs for supported sandboxes. Currently supported sandboxes are:

  * WildFire
  * CrowdStrike
  * JoeSecurity
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 218725c8-5f2a-438c-8b00-39eb76656d1f
    type: start
    task:
      id: 218725c8-5f2a-438c-8b00-39eb76656d1f
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1590,
          "y": 70
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
    continueonerrortype: ""
  "3":
    id: "3"
    taskid: bd46d172-dfb1-43e4-8904-643571582a5d
    type: title
    task:
      id: bd46d172-dfb1-43e4-8904-643571582a5d
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1590,
          "y": 860
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
    continueonerrortype: ""
  "12":
    id: "12"
    taskid: e0390fd8-4e73-42bc-8fdb-8480bf9af4d9
    type: condition
    task:
      id: e0390fd8-4e73-42bc-8fdb-8480bf9af4d9
      version: -1
      name: Is JoeSecurity sandbox enabled?
      description: Returns 'yes' if integration brand is available. Otherwise returns 'no'.
      type: condition
      iscommand: false
      brand: ""
      scriptName: IsIntegrationAvailable
    nexttasks:
      "no":
      - "3"
      "yes":
      - "29"
    scriptarguments:
      brandname:
        simple: JoeSecurityV2
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 510,
          "y": 390
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
    results:
    - brandInstances
    continueonerrortype: ""
  "28":
    id: "28"
    taskid: 603eed0e-4be1-4e78-81cc-1ee19961ac3b
    type: playbook
    task:
      id: 603eed0e-4be1-4e78-81cc-1ee19961ac3b
      version: -1
      name: Detonate URL - WildFire v2.1
      playbookName: Detonate URL - WildFire v2.1
      type: playbook
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      URL:
        complex:
          root: inputs.URL
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 1350,
          "y": 690
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
    continueonerrortype: ""
  "29":
    id: "29"
    taskid: e24eb7cd-22e4-48c7-8093-05bca0ceab7a
    type: playbook
    task:
      id: e24eb7cd-22e4-48c7-8093-05bca0ceab7a
      version: -1
      name: Detonate URL - JoeSecurity
      playbookName: Detonate URL - JoeSecurity
      type: playbook
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      Interval:
        simple: "1"
      Timeout:
        simple: "1200"
      URL:
        complex:
          root: inputs.URL
      EmailNotification:
        simple: "False"
      FastMode:
        simple: "false"
      FullDisplay:
        simple: "True"
      HybridCodeAnalysis:
        simple: "True"
      InternetAccess:
        simple: "True"
      LiveInteraction:
        simple: "False"
      SSLInspection:
        simple: "False"
      StartAsNormalUser:
        simple: "False"
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 510,
          "y": 690
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 6adfc95d-487a-4753-846f-d1a4c14204b1
    type: condition
    task:
      id: 6adfc95d-487a-4753-846f-d1a4c14204b1
      version: -1
      name: Is CrowdStrike Falcon Intelligence Sandbox enabled?
      description: Returns 'yes' if the CrowdStrike Falcon Intelligence Sandbox integration is available.
      scriptName: IsIntegrationAvailable
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "3"
      "yes":
      - "30"
    scriptarguments:
      brandname:
        simple: CrowdStrike Falcon Sandbox V2
    results:
    - brandInstances
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 920,
          "y": 390
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: f1f3ca4a-6436-40b5-8f34-84f3328b1c6c
    type: condition
    task:
      id: f1f3ca4a-6436-40b5-8f34-84f3328b1c6c
      version: -1
      name: Is there a URL?
      description: Is there a URL?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "6"
      - "12"
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: inputs.URL
            iscontext: true
          right:
            value: {}
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1590,
          "y": 220
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 51bb2a80-7e44-44ed-8a77-24d48ecb48e9
    type: condition
    task:
      id: 51bb2a80-7e44-44ed-8a77-24d48ecb48e9
      version: -1
      name: Is Wildfire enabled?
      description: Returns 'yes' if the WildFire integration is available.
      scriptName: IsIntegrationAvailable
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "3"
      "yes":
      - "28"
    scriptarguments:
      brandname:
        simple: WildFire-v2
    results:
    - brandInstances
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1350,
          "y": 390
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "30":
    id: "30"
    taskid: 168a8223-f9d3-4957-87ac-5c7291406a0a
    type: playbook
    task:
      id: 168a8223-f9d3-4957-87ac-5c7291406a0a
      version: -1
      name: Detonate URL - CrowdStrike
      playbookName: Detonate URL - CrowdStrike
      type: playbook
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      AlertOS:
        complex:
          root: ${incident
          accessor: deviceosname}
          transformers:
          - operator: MapValuesTransformer
            args:
              input_values:
                value:
                  simple: Windows,Linux,Android
              mapped_values:
                value:
                  simple: '160: Windows 10,300: Linux Ubuntu 16.04,300: Linux Ubuntu 16.04'
      EnableTor:
        simple: "false"
      EnvironmentID:
        simple: '''160: Windows 10'''
      URL:
        complex:
          root: inputs.URL
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 920,
          "y": 690
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "12_3_no": 0.24,
      "4_3_no": 0.32,
      "5_3_#default#": 0.16,
      "5_4_yes": 0.77,
      "6_3_no": 0.38
    },
    "paper": {
      "dimensions": {
        "height": 855,
        "width": 1460,
        "x": 510,
        "y": 70
      }
    }
  }
inputs:
- key: URL
  value: {}
  required: false
  description: The details of the URL to search for.
  playbookInputQuery:
outputs:
- contextPath: WildFire.Report
  description: The Wildfire findings.
  type: string
- contextPath: AttackPattern
  description: The MITRE Attack pattern information.
  type: unknown
- contextPath: MITREATTACK
  description: Full MITRE data for the attack pattern.
  type: unknown
- contextPath: DBotScore
  description: DBotScore object.
  type: unknown
- contextPath: Joe
  description: The sanbox report of the URL analysis
  type: unknown
- contextPath: Joe.Submission.most_relevant_analysis
  description: The URL verdict of the sandbox analysis
  type: unknown
- contextPath: Joe.Analysis
  description: The sandbox analysis details
  type: unknown
- contextPath: csfalconx
  description: The sandbox analysis details
  type: unknown
fromversion: 6.8.0
tests:
- No tests (auto formatted)
contentitemexportablefields:
  contentitemfields: {}
