id: Detonate URL - Generic
version: -1
name: Detonate URL - Generic
description: |
  This playbook uploads, detonates URLs for supported sandboxes. Currently supported sandboxes are:

  * WildFire
  * CrowdStrike
  * JoeSecurity
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: de95415e-0608-4a99-8445-0c01ca7a9e36
    type: start
    task:
      id: de95415e-0608-4a99-8445-0c01ca7a9e36
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "5"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1590,
          "y": -90
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 9b3ee626-c603-43fa-85db-9366b19799a0
    type: title
    task:
      id: 9b3ee626-c603-43fa-85db-9366b19799a0
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1590,
          "y": 860
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: f309fe75-bca3-4529-801c-a4353198f34f
    type: condition
    task:
      id: f309fe75-bca3-4529-801c-a4353198f34f
      version: -1
      name: Is CrowdStrike Falcon Intelligence Sandbox enabled?
      description: Returns 'yes' if the CrowdStrike Falcon Intelligence Sandbox integration is available.
      scriptName: IsIntegrationAvailable
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "3"
      "yes":
      - "32"
    scriptarguments:
      brandname:
        simple: CrowdStrike Falcon Sandbox V2
    results:
    - brandInstances
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 920,
          "y": 390
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: b86cf972-8284-4f6c-8919-8ba61e8ea263
    type: condition
    task:
      id: b86cf972-8284-4f6c-8919-8ba61e8ea263
      version: -1
      name: Is there a URL?
      description: Is there a URL?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "33"
      - "34"
      - "35"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: inputs.URL
            iscontext: true
          right:
            value: {}
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1590,
          "y": 60
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 89e50404-2efb-4469-8006-49e7f9733a07
    type: condition
    task:
      id: 89e50404-2efb-4469-8006-49e7f9733a07
      version: -1
      name: Is Wildfire enabled?
      description: Returns 'yes' if the WildFire integration is available.
      scriptName: IsIntegrationAvailable
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "3"
      "yes":
      - "31"
    scriptarguments:
      brandname:
        simple: WildFire-v2
    results:
    - brandInstances
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1350,
          "y": 390
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: 3a50ed87-f1ee-422e-8871-309ecb4cc09f
    type: condition
    task:
      id: 3a50ed87-f1ee-422e-8871-309ecb4cc09f
      version: -1
      name: Is JoeSecurity sandbox enabled?
      description: Returns 'yes' if integration brand is available. Otherwise returns 'no'.
      scriptName: IsIntegrationAvailable
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "3"
      "yes":
      - "29"
    scriptarguments:
      brandname:
        simple: JoeSecurityV2
    results:
    - brandInstances
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 510,
          "y": 390
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "29":
    id: "29"
    taskid: 0945e7bc-f12b-4b3c-841a-bf946085e174
    type: playbook
    task:
      id: 0945e7bc-f12b-4b3c-841a-bf946085e174
      version: -1
      name: Detonate URL - JoeSecurity
      description: Deprecated. Use the joe-submit-url command instead.
      playbookName: Detonate URL - JoeSecurity
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      InternetAccess:
        simple: "True"
      Interval:
        simple: "1"
      ReportFileType:
        simple: html
      Timeout:
        simple: "1200"
      URL:
        complex:
          root: inputs.URL
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 510,
          "y": 690
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "31":
    id: "31"
    taskid: be152608-14b9-43c3-8ab3-2e9e3f87cb01
    type: regular
    task:
      id: be152608-14b9-43c3-8ab3-2e9e3f87cb01
      version: -1
      name: WildFire upload and detonate
      description: Uploads a URL of a webpage to WildFire for analysis.
      script: '|||wildfire-upload-url'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      extended_data:
        simple: "true"
      format:
        simple: xml
      polling:
        simple: "true"
      upload:
        complex:
          root: inputs.URL
      verbose:
        simple: "true"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1350,
          "y": 690
        }
      }
    note: false
    evidencedata:
      description:
        simple: Wildfire sandbox report
      customfields: {}
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "32":
    id: "32"
    taskid: f7b4fe53-1e42-4153-83a6-cc76d3ab3abb
    type: regular
    task:
      id: f7b4fe53-1e42-4153-83a6-cc76d3ab3abb
      version: -1
      name: CrowdStrike Falcon Intelligence Sandbox upload and detonate
      description: Submits a URL or FTP for sandbox analysis.
      script: '|||cs-fx-submit-url'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      environment_id:
        simple: '160: Windows 10'
      execution-timeout:
        simple: "600"
      polling:
        simple: "true"
      url:
        complex:
          root: inputs.URL
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 920,
          "y": 690
        }
      }
    note: false
    evidencedata:
      description:
        simple: Falcon Intelligence Sandbox report
      customfields: {}
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "33":
    id: "33"
    taskid: ab6cfa64-8e65-4408-8197-3efa1d983e6b
    type: title
    task:
      id: ab6cfa64-8e65-4408-8197-3efa1d983e6b
      version: -1
      name: WildFire sandbox
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1350,
          "y": 230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "34":
    id: "34"
    taskid: 17472b04-4725-4000-85a5-77e8d7ccad60
    type: title
    task:
      id: 17472b04-4725-4000-85a5-77e8d7ccad60
      version: -1
      name: CrowdStrike sandbox
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 920,
          "y": 230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "35":
    id: "35"
    taskid: b7eb1fd8-81dc-4423-8d60-1c90c19729a7
    type: title
    task:
      id: b7eb1fd8-81dc-4423-8d60-1c90c19729a7
      version: -1
      name: JoeSecurity sandbox
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "12"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 510,
          "y": 230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "12_3_no": 0.24,
      "4_3_no": 0.32,
      "5_3_#default#": 0.16,
      "6_3_no": 0.38
    },
    "paper": {
      "dimensions": {
        "height": 1015,
        "width": 1460,
        "x": 510,
        "y": -90
      }
    }
  }
inputs:
- key: URL
  value: {}
  required: false
  description: The details of the URL to search for.
  playbookInputQuery:
outputs:
- contextPath: WildFire.Report
  description: The Wildfire findings.
  type: string
- contextPath: AttackPattern
  description: The MITRE Attack pattern information.
  type: unknown
- contextPath: MITREATTACK
  description: Full MITRE data for the attack pattern.
  type: unknown
- contextPath: DBotScore
  description: DBotScore object.
  type: unknown
- contextPath: Joe
  description: The sanbox report of the URL analysis
  type: unknown
- contextPath: Joe.Submission.most_relevant_analysis
  description: The URL verdict of the sandbox analysis
  type: unknown
- contextPath: Joe.Analysis
  description: The sandbox analysis details
  type: unknown
- contextPath: csfalconx
  description: The sandbox analysis details
  type: unknown
tests:
- No tests (auto formatted)
fromversion: 6.8.0
