id: Domain Enrichment - Generic v2 - Test
version: -1
name: Email Address Enrichment - Generic v2.1 - Test
description: A test for email address enrichment. Currently, due to issues, the test does not check all domain squatting results or whether the email addresses were detected as internal or external.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: eefd07b6-b131-4aa4-815f-5ed0dc8c392c
    type: start
    task:
      id: eefd07b6-b131-4aa4-815f-5ed0dc8c392c
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "11"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": -260
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 270b5fd5-763c-4ea7-8dd7-e936ce301bb1
    type: regular
    task:
      id: 270b5fd5-763c-4ea7-8dd7-e936ce301bb1
      version: -1
      name: Set domains to context
      description: Sets a value into the context with the given context key
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      key:
        simple: Domain.Name
      value:
        simple: domainthatdoesntexis.co.uk
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 230,
          "y": 670
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 881e3be8-e7e0-4381-865f-372d3d4191b4
    type: regular
    task:
      id: 881e3be8-e7e0-4381-865f-372d3d4191b4
      version: -1
      name: Set email addresses to context
      description: Sets a value into the context with the given context key
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      key:
        simple: Account.Email.Address
      value:
        simple: '["geverwithnoname@domainthatdoesntexist.co.uk", "soso@demisto.com", "koko@demisto.com", "user1@domain.com","donotdelete@demisto.ninja"]'
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 670,
          "y": 670
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 0df56104-6800-4a35-8a82-30ddd960f4cf
    type: regular
    task:
      id: 0df56104-6800-4a35-8a82-30ddd960f4cf
      version: -1
      name: Delete context
      description: Deletes context for a fresh start of this test.
      type: regular
      iscommand: false
      brand: ""
      scriptName: DeleteContext
    nexttasks:
      '#none#':
      - "2"
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 490
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "yes"
    reputationcalc: 1
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 4b2d5084-35e5-4986-837a-6a8b10641765
    type: condition
    task:
      id: 4b2d5084-35e5-4986-837a-6a8b10641765
      version: -1
      name: Was there a case of domain squatting?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 230,
          "y": 1050
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualNumber
          left:
            value:
              complex:
                root: DBotScore
                accessor: Score
            iscontext: true
          right:
            value:
              simple: "2"
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: c8bd611e-42a9-4a65-8981-2186c22df99b
    type: title
    task:
      id: c8bd611e-42a9-4a65-8981-2186c22df99b
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 460,
          "y": 1480
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 88f4dae9-a0ef-4308-8cc3-9fdd0fb5615a
    type: regular
    task:
      id: 88f4dae9-a0ef-4308-8cc3-9fdd0fb5615a
      version: -1
      name: Make test fail
      description: Fail the test if domain squatting was not detected.
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      message:
        simple: Domain squatting should have been detected, but wasn't, or the user was not enriched using Active Directory.
    reputationcalc: 1
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 460,
          "y": 1250
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 04afcd78-7c23-478c-8b15-76893e409757
    type: condition
    task:
      id: 04afcd78-7c23-478c-8b15-76893e409757
      version: -1
      name: Was internal email enriched using Active Directory?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "6"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: Account.ID
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 670,
          "y": 1050
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: ac9f5576-dfad-4c55-82f5-e0ab6f855aca
    type: playbook
    task:
      id: ac9f5576-dfad-4c55-82f5-e0ab6f855aca
      version: -1
      name: Email Address Enrichment - Generic v2.1
      playbookName: Email Address Enrichment - Generic v2.1
      type: playbook
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "5"
      - "9"
    scriptarguments:
      Domain:
        complex:
          root: Domain
          accessor: Name
          transformers:
          - operator: uniq
      Email:
        complex:
          root: Account
          accessor: Email.Address
          transformers:
          - operator: uniq
      InternalDomains:
        complex:
          root: inputs.InternalDomains
          transformers:
          - operator: uniq
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 450,
          "y": 860
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 6adc0e8f-8dfa-4896-869d-f553f6c225ce
    type: title
    task:
      id: 6adc0e8f-8dfa-4896-869d-f553f6c225ce
      version: -1
      name: Test With Empty Inputs
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "12"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: 5ff91241-2a9b-4b24-860f-388d107bb911
    type: regular
    task:
      id: 5ff91241-2a9b-4b24-860f-388d107bb911
      version: -1
      name: Delete context
      description: Deletes context for a fresh start of this test.
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      all:
        simple: "yes"
    reputationcalc: 1
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 10
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: 01154d75-554d-4de6-8434-31db3faa7066
    type: playbook
    task:
      id: 01154d75-554d-4de6-8434-31db3faa7066
      version: -1
      name: Email Address Enrichment - Generic v2.1
      description: |-
        Enrich email addresses.
        - Get information from Active Directory for internal addresses
        - Get the domain-squatting reputation for external addresses
      playbookName: Email Address Enrichment - Generic v2.1
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      Domain:
        complex:
          root: Domain
          accessor: Name
          transformers:
          - operator: uniq
      Email:
        complex:
          root: Account
          accessor: Email.Address
          transformers:
          - operator: uniq
      InternalDomains:
        complex:
          root: inputs.InternalDomains
          transformers:
          - operator: uniq
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 450,
          "y": 190
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: 9d5af121-6061-455f-80e1-380661cc2bb4
    type: title
    task:
      id: 9d5af121-6061-455f-80e1-380661cc2bb4
      version: -1
      name: Test With Empty Inputs
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 350
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "5_6_yes": 0.57,
      "5_7_#default#": 0.42,
      "9_6_yes": 0.58,
      "9_7_#default#": 0.43
    },
    "paper": {
      "dimensions": {
        "height": 1805,
        "width": 820,
        "x": 230,
        "y": -260
      }
    }
  }
inputs:
- key: InternalDomains
  value:
    simple: demisto.com, demistodev.com, demisto.ninja
  required: false
  description: A comma-separated list of internal domains
  playbookInputQuery:
outputs: []
fromversion: 5.0.0
