contentitemexportablefields:
  contentitemfields:
    propagationLabels:
    - all
description: This playbook creates new address objects in the Prisma SASE Object section. Those objects can be used later on in other objects such as Security Rules.
id: Prisma SASE - Create Address Object
inputs:
- description: The address value (should match the type)
  key: IP
  playbookInputQuery:
  required: false
  value: {}
- description: Tenant services group ID. If not provided, the tsg_id integration parameter will be used as the default.
  key: TSGID
  playbookInputQuery:
  required: false
  value: {}
- description: |-
    The configuration folder group setting.
    The default value is 'Shared'
  key: Folder
  playbookInputQuery:
  required: false
  value:
    simple: Shared
- description: |-
    Possible Values:
    True -> Will Commit and Push Configuration
    False -> Manual Push will be required.
    Else --> Will ignore the push section and continue the playbook.
  key: AutoCommit
  playbookInputQuery:
  required: false
  value: {}
- description: |-
    IP Netmask: IP address or a network using the slash notation - ip_address/mask
    IP Range: Range of IP addresses using the notation ip_address-ip_address
    IP Wildcard: IP wildcard address in the format of an IPv4 address followed by a slash and a mask
    FQDN: Domain Name
  key: Type
  playbookInputQuery:
  required: false
  value: {}
- description: "Default: 50 \nThis input controls the limit size for the get IP objects command.\nThis will help to avoid object duplicates in the systems.\n"
  key: limit
  playbookInputQuery:
  required: false
  value:
    simple: "50"
name: Prisma SASE - Create Address Object
outputs:
- contextPath: PrismaSase
  type: unknown
- contextPath: PrismaSase.Address
  description: Created address object.
- contextPath: PrismaSase.Address.description
  description: Address description.
- contextPath: PrismaSase.Address.folder
  description: Address folder.
- contextPath: PrismaSase.Address.id
  description: Address ID.
- contextPath: PrismaSase.Address.type
  description: Address type.
- contextPath: PrismaSase.Address.address_value
  description: Address value.
- contextPath: PrismaSase.Address.name
  description: Address name.
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 73e9f923-ee52-4693-8196-f6a4c7b5cb0e
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 73e9f923-ee52-4693-8196-f6a4c7b5cb0e
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 120
        }
      }
  "1":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.IP
          operator: isNotEmpty
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Is there an IP?
      id: 5adacab1-a4cf-41aa-89b8-25cde871a6f0
      iscommand: false
      name: Is there an IP?
      type: condition
      version: -1
    taskid: 5adacab1-a4cf-41aa-89b8-25cde871a6f0
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 250
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      tsg_id:
        complex:
          root: inputs.TSGID
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Lists all addresses objects.
      id: 3689f7b1-bf06-4c7a-89ba-b650deb9f7f8
      iscommand: true
      name: Get IP objects
      script: '|||prisma-sase-address-object-list'
      type: regular
      version: -1
    taskid: 3689f7b1-bf06-4c7a-89ba-b650deb9f7f8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 690,
          "y": 410
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 060c4380-0f99-4a04-8338-c44b6cbdaa4b
      iscommand: false
      name: Done
      type: title
      version: -1
      description: ''
    taskid: 060c4380-0f99-4a04-8338-c44b6cbdaa4b
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1500
        }
      }
  "4":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.IP
          operator: notIn
          right:
            iscontext: true
            value:
              simple: PrismaSase.Address.address_value
      label: "yes"
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Are the IPs exist?
      id: 5f4a9cd4-8f7b-4170-800d-bc9ee601c150
      iscommand: false
      name: Are the IPs exist?
      type: condition
      version: -1
    taskid: 5f4a9cd4-8f7b-4170-800d-bc9ee601c150
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 690,
          "y": 600
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      address_value:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: inputs.IP
              operator: notIn
              right:
                iscontext: true
                value:
                  simple: PrismaSase.Address.address_value
          root: inputs.IP
          transformers:
          - operator: uniq
      name:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: inputs.IP
              operator: notIn
              right:
                iscontext: true
                value:
                  simple: PrismaSase.Address.address_value
          root: inputs.IP
          transformers:
          - operator: uniq
      tsg_id:
        complex:
          root: inputs.TSGID
      type:
        complex:
          root: inputs.Type
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Create a new address object.
      id: 9b9c246e-2b37-422b-81c4-cdc836d6b1d2
      iscommand: true
      name: Create new address object
      script: '|||prisma-sase-address-object-create'
      type: regular
      version: -1
    taskid: 9b9c246e-2b37-422b-81c4-cdc836d6b1d2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 940,
          "y": 780
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      folders:
        simple: Remote Networks, Mobile Users, Service Connections
      tsg_id:
        complex:
          root: inputs.TSGID
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Push the candidate configuration.
      id: 886727fa-b66e-4ebf-8b4e-c31e425ec809
      iscommand: true
      name: Push Config
      script: '|||prisma-sase-candidate-config-push'
      type: regular
      version: -1
    taskid: 886727fa-b66e-4ebf-8b4e-c31e425ec809
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 940,
          "y": 1325
        }
      }
  "7":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: inputs.AutoCommit
          operator: isEqualString
          right:
            value:
              simple: "True"
      label: Auto Commit
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.AutoCommit
          operator: isEqualString
          right:
            value:
              simple: "False"
      label: Manual
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      Auto Commit:
      - "6"
      Manual:
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Commit and push configuration to folders?
      id: 471f2e7b-835f-432f-8cbb-1076304e23a6
      iscommand: false
      name: Commit and push configuration to folders?
      type: condition
      version: -1
    taskid: 471f2e7b-835f-432f-8cbb-1076304e23a6
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 940,
          "y": 970
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc:
      body:
      cc:
      format: ""
      methods: []
      replyOptions:
      - Push
      - "No"
      subject:
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to:
    nexttasks:
      '#default#':
      - "3"
      Push:
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: 'Complete this task to push the configuration '
      id: 0bb91649-69cd-4eff-8741-15f147c5f3f4
      iscommand: false
      name: 'Complete this task to push the configuration '
      type: condition
      version: -1
    taskid: 0bb91649-69cd-4eff-8741-15f147c5f3f4
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 710,
          "y": 1150
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f5b7f9a9-17ab-4b0b-86af-3d37bafe8a10
      iscommand: false
      name: Check if the Name objects already exist
      type: title
      version: -1
      description: ''
    taskid: f5b7f9a9-17ab-4b0b-86af-3d37bafe8a10
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1210,
          "y": 440
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "1_3_#default#": 0.1,
      "4_3_#default#": 0.31,
      "8_6_Push": 0.39
    },
    "paper": {
      "dimensions": {
        "height": 1445,
        "width": 1140,
        "x": 450,
        "y": 120
      }
    }
  }
tests:
- No tests (auto formatted)
