name: Review Release Notes
on: pull_request

env:
  CHANGED_FILES_DELIMITER: ";"

jobs:
  release_notes_review:
    runs-on: ubuntu-latest
    if: github.repository == 'demisto/content'
    steps:
  
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
          cache: pip
      - name: Install SDK
        run: |
          pip install demisto-sdk
      
  
      - name: Review Release Notes
        run: |
          release_notes="Packs/QRadar/ReleaseNotes/1.0.3.md"
          echo "Release notes found in PR: ${release_notes}. Starting docs review..."

          Utils/github_workflow_scripts/run_docs_review.py --changed_files "$release_notes" --delimiter "${{ env.CHANGED_FILES_DELIMITER }}"
